### ISSUE TITLE
[DOC] incorrect npm package name in usage section

### ISSUE THREAD

**Issue by manu-mishra** [awslabs/agents-for-amazon-bedrock-blueprints#19]
**Describe the issue**
The package name in this section is miss-spelled, it should be ```npm i @aws/agents-for-amazon-bedrock-blueprints``` instead of ```npm i @aws/agents-for-amazaon-bedrock-blueprints```  
https://github.com/awslabs/agents-for-amazon-bedrock-blueprints?tab=readme-ov-file#usage

**Comment by divekarshubham** [comment]
Thank you for bringing this up. The fix has been merged.
